# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Shuvo Saha'
tagline:          'Software Engineer'
description:      'Personal website.'
url:              'https://sahashuvo.github.io/'
baseurl:          /

author:
  name:           'Shuvo Saha'
  url:            mailto:'sahashuvo@gmail.com'

paginate:         5
