# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Shuvo Saha'
tagline:          'Software Engineer'
description:      'Personal website.'
url:              'https://sahashuvo.github.io/'
baseurl:          'https://sahashuvo.github.io/'

author:
  name:           'Shuvo Saha'
  url:            mailto:'sahashuvo@gmail.com'

paginate:         5
