# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Shuvo Saha'
tagline:          'Software Engineer'
description:      'Software Engineer'
url:              'https://sahashuvo.github.io'
baseurl:          /

author:
  name:           'Shuvo Saha'
  url:            mailto:'sahashuvo@gmail.com'

paginate:         5
